# Project Title:
### Data-Driven Ad Campaign Optimization

# Project Domain:
### Digital Marketing Analytics

# Problem Statement


The objective of this project is to analyze and optimize digital ad campaigns using data-driven techniques. The primary goal is to identify and evaluate Key Performance Indicators (KPIs) such as CTR, CVR, CPC, and ROAS that significantly influence campaign effectiveness. By applying exploratory data analysis (EDA), feature engineering, and statistical methods, we aim to generate actionable insights that can guide marketing teams to improve campaign engagement, increase conversions, and maximize Return on Investment (ROI).

# Role
### Data Analyst
Responsible for 
- data cleaning, 
- exploration, 
- statistical analysis, 
- visualization, 
- insight generation

# Tools & Technologies
1) Python (Pandas, NumPy, Matplotlib, Seaborn, Plotly)
2) Jupyter Notebook / VS Code
3) MySQL (for querying structured data)
4) Excel (for basic dashboarding if needed)
5) Power BI or Tableau (optional, for visualization dashboard)

# Step 1: Data Collection / Import

In [2]:
import numpy as np
import pandas as pd
import matplotlib as plt
from datetime import datetime

In [3]:
df=pd.read_csv(r"c:\Users\ADMIN\Downloads\ad_campaign_completely_raw_dataset (1).csv")
df

,campaign_id,campaign_name,platform,date,impressions,clicks,cost,conversions,revenue,ctr,...,conversion_rate,roas,ad_type,audience_segment,device_type,region,bounce_rate,avg_session_duration,engagement_rate,ad_position
0,1001,Summer Sale,Unknown,"March 10, 2024",33144.0,1836,428.66,494.0,3697.13,5.54,...,26.91,8.62,Search Ad,NaN,Deskotp,India,38.0,NaN,30.0,Top
1,1002,!!!,Facebook Ads,15-02-2024,32780.0,1846,431.54,97.0,1834.94,5.63,...,5.25,4.25,Display Ad,New Users,Unknown,Unknown,20.0,2m 15s,39.0,Bottom
2,1003,NaN,NaN,NaN,28847.0,3890,85.31,261.0,4562.69,13.48,...,6.71,53.48,search_add,Returning Customers,Mobile,Europe,38.0,NaN,54.0,Side
3,1004,Summer Sale,Gogle Adz,15-02-2024,21367.0,4922,449.65,146.0,2968.74,23.04,...,2.97,6.60,NaN,New Users,Mobl,India,34.0,NaN,43.0,NaN
4,1005,Black Friday Deal,Google Ads,"March 10, 2024",36303.0,4947,176.97,313.0,3103.35,13.63,...,6.33,17.54,Video Ad,Returning Customers,Unknown,Unknown,31.0,3m 40s,38.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,1732,Summer Sale,FB ads,2024/04/05,36176.0,4362,432.64,449.0,3731.56,12.06,...,10.29,8.63,AdX,Returning Customers,Unknown,Unknown,31.0,3m 40s,49.0,NaN
1196,1100,Unknown_campaign,NaN,2024/04/05,37920.0,4346,382.42,335.0,4444.86,11.46,...,7.71,11.62,Video Ad,unkown_segment,NaN,USA,23.0,NaN,42.0,Side
1197,1099,NaN,Gogle Adz,2024-01-01,8537.0,1758,464.99,490.0,2155.98,20.59,...,27.87,4.64,NaN,unkown_segment,Unknown,India,47.0,NaN,38.0,Bottom
1198,1678,Unknown_campaign,FB ads,2024/04/05,7547.0,4967,427.60,136.0,3809.75,65.81,...,2.74,8.91,Search Ad,Returning Customers,Unknown,NaN,26.0,NaN,44.0,Bottom
1199,1829,Black Friday Deal,Facebook Ads,2024-01-01,7814.0,773,405.51,220.0,2067.97,9.89,...,28.46,5.10,AdX,Returning Customers,NaN,USA,40.0,NaN,50.0,Side

In [4]:
df.describe()

,campaign_id,impressions,cost,conversions,revenue,ctr,cpc,conversion_rate,roas,bounce_rate,engagement_rate
count,1200.000000,1195.000000,1192.000000,1193.000000,1194.000000,1189.000000,1189.000000,1189.000000,1192.000000,1195.000000,1193.000000
mean,1502.479167,27658.066946,265.122659,249.744342,2778.121039,12.971985,0.228545,20.339403,15.044908,34.321339,44.696563
std,287.972886,13083.905300,131.358002,141.854375,1301.767604,12.724070,0.430080,35.806968,13.792969,8.727717,8.498725
min,1001.000000,5054.000000,50.200000,10.000000,508.070000,0.250000,0.010000,0.210000,1.040000,20.000000,30.000000
25%,1250.750000,16173.500000,140.575000,131.000000,1648.747500,4.960000,0.060000,5.010000,6.627500,27.000000,37.000000
50%,1505.000000,27782.000000,255.875000,241.000000,2738.860000,9.380000,0.100000,9.820000,10.315000,34.000000,45.000000
75%,1749.250000,39147.500000,378.585000,375.000000,3914.715000,16.410000,0.210000,18.930000,18.610000,42.000000,52.000000
max,2000.000000,49865.000000,499.900000,499.000000,4997.340000,97.460000,4.570000,333.000000,88.030000,49.000000,59.000000

In [52]:
df.sample()

,campaign_id,campaign_name,platform,date,impressions,clicks,cost,conversions,revenue,ctr,...,conversion_rate,roas,ad_type,audience_segment,device_type,region,bounce_rate,avg_session_duration,engagement_rate,ad_position
163,1164,Unknown_campaign,google_ads,2024-01-01,21519.0,4895.0,325.85,107.0,838.38,22.75,...,2.19,2.57,search_add,NaN,Mobile,India,24.0,NaN,43.0,NaN

# Step 2: Data Cleaning:

## 1.1 Initial Inspection (Before Cleaning Starts)
Method:
df.head(), df.tail(), df.sample()

df.info() → data types + nulls

df.describe() → numeric summary

df.columns → column names check

Goal: Data structure, size, आणि problems समजून घेणं.

In [53]:
df.head()

,campaign_id,campaign_name,platform,date,impressions,clicks,cost,conversions,revenue,ctr,...,conversion_rate,roas,ad_type,audience_segment,device_type,region,bounce_rate,avg_session_duration,engagement_rate,ad_position
0,1001,Summer Sale,Unknown,2024-03-10,33144.0,1836.0,428.66,494.0,3697.13,5.54,...,26.91,8.62,Search Ad,NaN,Deskotp,India,38.0,NaN,30.0,Top
1,1002,!!!,Facebook Ads,2024-02-15,32780.0,1846.0,431.54,97.0,1834.94,5.63,...,5.25,4.25,Display Ad,New Users,Unknown,Unknown,20.0,2m 15s,39.0,Bottom
2,1003,NaN,NaN,2024-02-15,28847.0,3890.0,85.31,261.0,4562.69,13.48,...,6.71,53.48,search_add,Returning Customers,Mobile,Europe,38.0,NaN,54.0,Side
3,1004,Summer Sale,Gogle Adz,2024-02-15,21367.0,4922.0,449.65,146.0,2968.74,23.04,...,2.97,6.60,NaN,New Users,Mobl,India,34.0,NaN,43.0,NaN
4,1005,Black Friday Deal,Google Ads,2024-03-10,36303.0,4947.0,176.97,313.0,3103.35,13.63,...,6.33,17.54,Video Ad,Returning Customers,Unknown,Unknown,31.0,3m 40s,38.0,NaN

In [7]:
# sarv column name lower case madhe ahe. ya thikane kahi null values ahet. numerical va catagorical donhi column ahet.
# impressions ky ahe te samjun ghene. what is conversion. what is roas. 
# there is some null values available in dataset. in some where there is unlown insted of nulls.

In [8]:
df.tail()

,campaign_id,campaign_name,platform,date,impressions,clicks,cost,conversions,revenue,ctr,...,conversion_rate,roas,ad_type,audience_segment,device_type,region,bounce_rate,avg_session_duration,engagement_rate,ad_position
1195,1732,Summer Sale,FB ads,2024/04/05,36176.0,4362,432.64,449.0,3731.56,12.06,...,10.29,8.63,AdX,Returning Customers,Unknown,Unknown,31.0,3m 40s,49.0,NaN
1196,1100,Unknown_campaign,NaN,2024/04/05,37920.0,4346,382.42,335.0,4444.86,11.46,...,7.71,11.62,Video Ad,unkown_segment,NaN,USA,23.0,NaN,42.0,Side
1197,1099,NaN,Gogle Adz,2024-01-01,8537.0,1758,464.99,490.0,2155.98,20.59,...,27.87,4.64,NaN,unkown_segment,Unknown,India,47.0,NaN,38.0,Bottom
1198,1678,Unknown_campaign,FB ads,2024/04/05,7547.0,4967,427.60,136.0,3809.75,65.81,...,2.74,8.91,Search Ad,Returning Customers,Unknown,NaN,26.0,NaN,44.0,Bottom
1199,1829,Black Friday Deal,Facebook Ads,2024-01-01,7814.0,773,405.51,220.0,2067.97,9.89,...,28.46,5.10,AdX,Returning Customers,NaN,USA,40.0,NaN,50.0,Side

In [9]:
# there is same observation like df.head()

In [10]:
df.sample()

,campaign_id,campaign_name,platform,date,impressions,clicks,cost,conversions,revenue,ctr,...,conversion_rate,roas,ad_type,audience_segment,device_type,region,bounce_rate,avg_session_duration,engagement_rate,ad_position
621,1622,!!!,NaN,"March 10, 2024",15239.0,380,247.26,136.0,2973.48,2.49,...,35.79,12.03,Video Ad,NaN,Desktop,Europe,28.0,NaN,30.0,Bottom

In [11]:
# out of 21 column there is 13 is numerical column and remaining are catagorical column

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   campaign_id           1200 non-null   int64
 1   campaign_name         1004 non-null   object
 2   platform              1030 non-null   object
 3   date                  941 non-null    object
 4   impressions           1195 non-null   float64
 5   clicks                1200 non-null   object
 6   cost                  1192 non-null   float64
 7   conversions           1193 non-null   float64
 8   revenue               1194 non-null   float64
 9   ctr                   1189 non-null   float64
 10  cpc                   1189 non-null   float64
 11  conversion_rate       1189 non-null   float64
 12  roas                  1192 non-null   float64
 13  ad_type               979 non-null    object
 14  audience_segment      908 non-null    object
 15  device_type           1008 non-null   object
 16  region                968 non-null    object
 17  bounce_rate           1195 non-null   float64
 18  avg_session_duration  561 non-null    object
 19  engagement_rate       1193 non-null   float64
 20  ad_position           734 non-null    object
dtypes: float64(10), int64(1), object(10)
memory usage: 197.0+ KB

In [13]:
# campaign id madhe, clicks ek pan null value nahiye. 
# 200 chya aspas null values 3 column(campaign_name,platform, device type). 
# cost to roas panryant je column ahet tyamadhe 10 to 20 null values ahet. 
# 300 chya aspas null vules( date, ad_type,audience_segment,region), 
# 400 chya asapass null values ad_possition madhe ahet. 
# sarvat jast null values avg_session_duration madhe ahet. 
# data type 3 prakarche ahet int. object, float.
# null value treat karavya lagatil 
# date column cha datatype object ahe tyala date madhe convert karave lagel
# clicks cha datatype object ahe tyala int madhe convert karave lagel
# avg session duration che formating karave lagel

In [14]:
# atta aplalyala deside karayache ahe ki sarvat jast null value asanara column avg_session_duration thevayacha ki nahi

In [15]:
df.columns

Index(['campaign_id', 'campaign_name', 'platform', 'date', 'impressions',
       'clicks', 'cost', 'conversions', 'revenue', 'ctr', 'cpc',
       'conversion_rate', 'roas', 'ad_type', 'audience_segment', 'device_type',
       'region', 'bounce_rate', 'avg_session_duration', 'engagement_rate',
       'ad_position'],
      dtype='object')

In [16]:
df['clicks']

0       1836
1       1846
2       3890
3       4922
4       4947
        ...
1195    4362
1196    4346
1197    1758
1198    4967
1199     773
Name: clicks, Length: 1200, dtype: object

In [17]:
null_percentage=df['clicks'].isnull().mean()*100
print('missing=',null_percentage)

missing= 0.0

In [18]:
null_pecentage=df['avg_session_duration'].isnull().mean()*100
print('missing=',null_pecentage)

missing= 53.25

In [19]:
# mhange 53% value null ahet tr shakyato to column thevaycha praytn karava. khupach 70% value null asatil tr drop karava

In [20]:
# date column cha data type change karuya

In [21]:
df['date'].dtype

dtype('O')

In [22]:
df['date']

0       March 10, 2024
1           15-02-2024
2                  NaN
3           15-02-2024
4       March 10, 2024
             ...
1195        2024/04/05
1196        2024/04/05
1197        2024-01-01
1198        2024/04/05
1199        2024-01-01
Name: date, Length: 1200, dtype: object

In [23]:
df['date'].unique()

array(['March 10, 2024', '15-02-2024', nan, '2024/04/05', '2024-01-01'],
      dtype=object)

In [24]:
df.loc[df['date'] == 'March 10, 2024', 'date'] = '10-03-2024'
df.loc[df['date'] == '2024/04/05', 'date'] = '05-04-2024'
df.loc[df['date'] == '2024-01-01', 'date'] = '01-01-2024'
df['date'].unique()

array(['10-03-2024', '15-02-2024', nan, '05-04-2024', '01-01-2024'],
      dtype=object)

In [25]:
df['date']=df['date'].fillna(method='bfill')

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_13220\2489334493.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['date']=df['date'].fillna(method='bfill')

In [26]:
df['date'].isnull().sum()

np.int64(0)

In [27]:
df['date']

0       10-03-2024
1       15-02-2024
2       15-02-2024
3       15-02-2024
4       10-03-2024
           ...
1195    05-04-2024
1196    05-04-2024
1197    01-01-2024
1198    05-04-2024
1199    01-01-2024
Name: date, Length: 1200, dtype: object

In [28]:
# Convert from string (object) to datetime, specifying dayfirst=True
df['date'] = pd.to_datetime(df['date'], format='%d-%m-%Y', errors='coerce')

In [29]:
df['date'].dtype

dtype('<M8[ns]')

In [30]:
#  atta clicks column baghu

In [31]:
df['clicks']

0       1836
1       1846
2       3890
3       4922
4       4947
        ...
1195    4362
1196    4346
1197    1758
1198    4967
1199     773
Name: clicks, Length: 1200, dtype: object

In [32]:
df['clicks'].unique()

array(['1836', '1846', '3890', '4922', '4947', '2811', '3797', '3659',
       '1180', '789', '475', '130', '4607', '3419', '1328', '1880',
       '1216', '984', '792', '1076', '2438', '4944', '4074', '1218',
       '4849', '4244', '4851', '1848', '3873', '4092', '773', '3550',
       '3008', '419', '1098', '2090', '2101', '3393', '2738', '2437',
       '143', '2262', '1182', '3661', '3732', '146', '451', '4596',
       '1029', '1513', '2735', '346', '4688', '2405', '597', '598',
       '3299', '4788', '1872', '1826', '4058', '316', '3952', '3163',
       '4519', '913', '1684', '4515', '1276', '1279', '4921', '2537',
       '2246', '3617', '3395', '2069', '2335', '386', '4274', '3147',
       '1858', '362', '2010', '4010', '4666', '1609', '845', '4326',
       '2874', '2068', '195', '872', '2158', '521', '4860', '3096',
       '3154', '1415', '1758', '4346', '3440', '1197', '3707', '1514',
       '4292', '3830', '532', '380', '2873', '2503', '4383', '504', '737',
       '3127', '4642', '1137', '4781', '1900', '4152', '1110', '3160',
       '3866', '1966', '4233', '716', '1688', '4775', '774', '2877',
       '554', '234', '3742', '3438', '1140', '436', '3164', '2208',
       '4808', '4948', '245', '1984', '4490', '4120', '2779', '3169',
       '2859', '2607', '858', '3126', '426', '3637', '2065', '2511',
       '4791', '2362', '1048', '2121', '2131', '4895', '1433', '3680',
       '4514', '875', '176', '1904', '4474', '3255', '102', '2075',
       '3536', '2277', '4761', '1297', '1708', '2200', '4693', '3368',
       '3065', '3256', '4347', '3448', '2356', '223', '2458', '4930',
       '2520', '4969', '1977', '3359', '3483', '1777', '743', '4506',
       '570', '615', '4343', '2932', '3135', '1762', '4100', '4977',
       '1122', '2587', '964', '1638', '1211', '3664', '4333', '2459',
       '3651', '4282', '3917', '4481', '2677', '2213', '1865', '2255',
       '2269', '1492', '1375', '3767', '3428', '2281', '1818', '1348',
       '2693', '3940', '1473', '4843', '4762', '4673', '2395', '1066',
       '1737', '4234', '4190', '4531', '693', '2777', '1121', '2349',
       '4020', '2094', '4871', '1174', '1347', '1674', '4460', '3969',
       '256', '3597', '925', '4192', '4883', '2359', '4570', '1075',
       '1278', '296', '3434', '1728', '158', '4153', '290', '909', '1830',
       '1744', '1461', '2970', '882', '3937', '4837', '2913', '781',
       '2979', '3252', '3836', '4240', '983', '3173', '2570', '1146',
       '2117', '177', '4357', '3889', '4345', '2379', '4597', '1510',
       '2788', '1224', '4966', '4372', '2733', '1399', '536', '307',
       '423', '505', '1002', '3362', '1648', '1769', '3503', '1293',
       '1832', '400', '3018', '3339', '4081', '2985', '3443', '1564',
       '1866', '4407', '2481', '4711', '3402', '1055', '1385', '4075',
       '3901', '4096', '2181', '526', '1179', '3286', '2813', '2575',
       '4373', '4816', '119', '2846', '3688', '2303', '3123', '4915',
       '1373', '3563', '4757', '3036', '1680', '2278', '3493', '433',
       '4301', '4424', '4179', '1805', '1367', '3236', '4320', '2764',
       '1212', '744', '643', '1947', '4237', '1168', '761', '3721',
       '2386', '4054', '332', '3915', '4927', '2323', '3390', '1814',
       '3429', '510', '4149', '2229', '2724', '3054', '3027', '330',
       '1964', '4411', '3855', '4789', '4455', '3326', '4028', '2845',
       '1885', '205', '2221', '4463', '3389', '2338', '3408', '3523',
       '524', '4348', '2168', '1417', '2922', '2222', '3592', '4710',
       '320', '1604', '764', '100', '784', '1044', '3980', '2792', '594',
       '280', '1949', '134', '3693', '4112', '220', '2612', '339', '1341',
       '3158', '375', '136', '1160', '389', '4891', '579', '4477', '4675',
       '2890', '2470', '3055', '2056', '3768', '890', '4088', '1575',
       '852', '4283', '1445', '4733', '4580', '3603', '1046', '2468',
       '1602', '3598', '1955', '4997', '1144', '616', '1695', '646',
       '3254', '2072', '162', '3192', '1027', '3231', '145', '2036',
       '139', '2063', '3101', '3412', '3102', '2533', '3894', '2558',
       '2055', '2939', '3506', '2507', '4610', '4263', '3612', '359',
       '4503', '2996', '3814', '1778', '3774', '3579', '1960', '3939',
       '4855', '4171', '2434', '4822', '2559', '2070', '1394', '2135',
       '459', '3262', '705', '3151', '668', '3568', '4866', '535', '2723',
       '2972', '4529', '4039', '2493', '3656', '4131', '1584', '2544',
       '2171', '1340', '2466', '2767', '1222', '3648', '4664', '1308',
       '4795', '4217', '1948', '4912', '103', '4321', '454', '2828',
       '3976', '528', '4154', '557', '1734', '1062', '4647', '1951',
       '4535', '2391', '2604', '1521', '193', '341', '2642', '4590',
       '2203', '3182', '623', '4953', '4632', '4934', '4003', '2275',
       '2445', '3226', '1472', '3653', '899', '3560', '1427', '952',
       '1776', '2283', '4587', '2837', '1497', '4132', '2315', '4306',
       '3565', '1937', '4457', '640', '4794', '518', '4867', '2749',
       '3334', '1800', '3474', '4753', '4123', '4800', '936', '4683',
       '546', '344', '3763', '445', '530', '3295', '703', '2148', '4134',
       '2451', '3259', '4919', '1331', '2353', '853', '2730', '2889',
       '4434', '2933', '2532', '4222', '1426', '1395', '3769', '3019',
       '3946', '4796', '1551', '3375', '3871', '4130', '2830', '4709',
       '2119', '4884', '1876', '2652', '4952', '2350', '1572', '796',
       '2973', '2572', '191', '4996', '4967', '4875', '4126', '659',
       '2965', '425', '1983', '3807', '4247', '2238', '3310', '1020',
       '1158', '3929', '968', '3037', '993', '2300', '1232', '4471',
       '4617', '4605', '1082', '151', '1687', '485', '1391', '3446',
       '1679', '3355', '2045', '107', '4121', '4225', '4751', '2663',
       '3508', '2711', '932', '4534', '2631', '1925', '2044', '229',
       '2531', '3319', '4362', '3331', '4638', '1784', '4815', '2342',
       '1722', '922', '3341', '2471', '1968', '3695', '1982', '4598',
       '4545', '2363', '4095', '1173', '4309', '3857', '1185', '1496',
       '3201', '1268', '4024', '1291', '2396', '4305', '3249', '3753',
       '1595', '881', '2699', '3270', '2290', '4661', '2411', '3064',
       '3880', '527', '4736', '3697', '2282', '4482', '2566', '1988',
       '1164', '1592', '857', '1006', '2949', '2695', '4792', '4197',
       '1235', '1438', '3128', '448', '1153', '1871', '3679', '4510',
       '4315', '2740', '121', '2725', '2256', '297', '540', '1073',
       '1425', '1499', '931', '4903', '3312', '2864', '1856', '1919',
       '1142', '4833', '674', '3149', '2848', '4286', '106', '3583',
       '2233', '4202', '3422', '1535', '1920', '1191', '2868', '2694',
       '812', '3610', '1247', '1113', '4960', '4045', '2214', '1133',
       '1556', '2980', '1280', '586', '4556', '1963', '4137', '1424',
       '3199', '1862', '3296', '3117', '4261', '1512', '1710', '4254',
       '2408', '299', '2264', '3748', '2891', '1145', '893', '1366',
       '487', '3899', '1475', '2768', '4817', '3802', '4991', '2265',
       '4427', '1706', '4174', '3973', '870', '4018', '1430', '2747',
       '260', '885', '1084', '3079', '2948', '2919', '458', '4191',
       '3780', '2967', '4291', '3432', '2800', '871', '2993', '1819',
       '940', '1068', '4355', '4872', '2370', '424', '353', '447', '3851',
       '4748', '135', '1703', '995', '3140', '4242', '181', '1381',
       '3031', '3865', '2196', '915', '3949', '1954', '1390', '4198',
       '2861', '3227', '3883', '2261', '3989', '4296', '677', '3632',
       '2309', '1309', '3521', '886', '697', '2038', '3325', '3043',
       '3542', '772', '4016', '967', '1627', '1788', '2061', '908',
       '1529', '161', '4679', '2705', '2357', '1707', '4548', '1825',
       '2961', '2162', '4119', '4553', '1455', 'missing'], dtype=object)

In [33]:
df.loc[df['clicks'] == 'missing']

,campaign_id,campaign_name,platform,date,impressions,clicks,cost,conversions,revenue,ctr,...,conversion_rate,roas,ad_type,audience_segment,device_type,region,bounce_rate,avg_session_duration,engagement_rate,ad_position
990,1991,!!!,FB ads,2024-04-05,39376.0,missing,121.88,183.0,1981.68,NaN,...,NaN,16.26,NaN,New Users,NaN,NaN,46.0,NaN,31.0,Top
991,1992,NaN,Facebook Ads,2024-03-10,36617.0,missing,387.17,200.0,583.41,NaN,...,NaN,1.51,Display Ad,NaN,Mobile,Europe,49.0,NaN,58.0,NaN
992,1993,Summer Sale,Google Ads,2024-03-10,10282.0,missing,NaN,206.0,3650.40,NaN,...,NaN,NaN,NaN,New Users,Unknown,India,30.0,2m 15s,49.0,NaN
993,1994,Holiday Offer,NaN,2024-02-15,35903.0,missing,NaN,NaN,1805.29,NaN,...,NaN,NaN,Display Ad,New Users,Unknown,USA,48.0,2m 15s,NaN,NaN
994,1995,Unknown_campaign,Unknown,2024-01-01,45312.0,missing,NaN,NaN,NaN,NaN,...,NaN,NaN,AdX,NaN,NaN,India,42.0,2m 15s,NaN,Bottom
995,1996,Summer Sale,Google Ads,2024-02-15,NaN,missing,NaN,NaN,NaN,NaN,...,NaN,NaN,Display Ad,NaN,Desktop,NaN,NaN,NaN,NaN,Top
996,1997,Unknown_campaign,FB ads,2024-04-05,NaN,missing,NaN,NaN,NaN,NaN,...,NaN,NaN,Video Ad,New Users,NaN,Unknown,NaN,3m 40s,NaN,Bottom
997,1998,Black Friday Deal,Gogle Adz,2024-02-15,NaN,missing,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,unkown_segment,Mobile,Unknown,NaN,3m 40s,NaN,NaN
998,1999,Unknown_campaign,Google Ads,2024-02-15,NaN,missing,NaN,NaN,NaN,NaN,...,NaN,NaN,Video Ad,NaN,Mobl,India,NaN,NaN,NaN,Bottom
999,2000,!!!,Gogle Adz,2024-04-05,NaN,missing,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Deskotp,NaN,NaN,NaN,NaN,NaN
1181,1992,NaN,Facebook Ads,2024-02-15,36617.0,missing,387.17,200.0,583.41,NaN,...,NaN,1.51,Display Ad,NaN,Mobile,Europe,49.0,NaN,58.0,NaN

In [34]:
# atta apalykade ase 11 rows ahet tyanchi value 'missing' ahe tya missing la null ne replace karayache.
# nantar column la string to int karayche 
# mg null value la mean ne fill karayache
df['clicks'] = df['clicks'].replace('missing', np.nan)

In [35]:
# Step 1: Convert to numeric (this will turn non-numeric like NaN or 'missing' into np.nan)
df['clicks'] = pd.to_numeric(df['clicks'], errors='coerce')
df['clicks'].dtype

dtype('float64')

In [36]:
# avg session duration che formating adhi karu mag sarv numeric column chya null value fill karu mean kinva median ne

In [37]:
df['avg_session_duration']

0          NaN
1       2m 15s
2          NaN
3          NaN
4       3m 40s
         ...
1195    3m 40s
1196       NaN
1197       NaN
1198       NaN
1199       NaN
Name: avg_session_duration, Length: 1200, dtype: object

In [38]:
df['avg_session_duration'].unique()

array([nan, '2m 15s', '3m 40s'], dtype=object)

In [39]:
df['avg_session_duration'].isnull().sum()

np.int64(639)

In [40]:
df.head()

,campaign_id,campaign_name,platform,date,impressions,clicks,cost,conversions,revenue,ctr,...,conversion_rate,roas,ad_type,audience_segment,device_type,region,bounce_rate,avg_session_duration,engagement_rate,ad_position
0,1001,Summer Sale,Unknown,2024-03-10,33144.0,1836.0,428.66,494.0,3697.13,5.54,...,26.91,8.62,Search Ad,NaN,Deskotp,India,38.0,NaN,30.0,Top
1,1002,!!!,Facebook Ads,2024-02-15,32780.0,1846.0,431.54,97.0,1834.94,5.63,...,5.25,4.25,Display Ad,New Users,Unknown,Unknown,20.0,2m 15s,39.0,Bottom
2,1003,NaN,NaN,2024-02-15,28847.0,3890.0,85.31,261.0,4562.69,13.48,...,6.71,53.48,search_add,Returning Customers,Mobile,Europe,38.0,NaN,54.0,Side
3,1004,Summer Sale,Gogle Adz,2024-02-15,21367.0,4922.0,449.65,146.0,2968.74,23.04,...,2.97,6.60,NaN,New Users,Mobl,India,34.0,NaN,43.0,NaN
4,1005,Black Friday Deal,Google Ads,2024-03-10,36303.0,4947.0,176.97,313.0,3103.35,13.63,...,6.33,17.54,Video Ad,Returning Customers,Unknown,Unknown,31.0,3m 40s,38.0,NaN

In [41]:
df['impressions']

0       33144.0
1       32780.0
2       28847.0
3       21367.0
4       36303.0
         ...
1195    36176.0
1196    37920.0
1197     8537.0
1198     7547.0
1199     7814.0
Name: impressions, Length: 1200, dtype: float64

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   campaign_id           1200 non-null   int64
 1   campaign_name         1004 non-null   object
 2   platform              1030 non-null   object
 3   date                  1200 non-null   datetime64[ns]
 4   impressions           1195 non-null   float64
 5   clicks                1189 non-null   float64
 6   cost                  1192 non-null   float64
 7   conversions           1193 non-null   float64
 8   revenue               1194 non-null   float64
 9   ctr                   1189 non-null   float64
 10  cpc                   1189 non-null   float64
 11  conversion_rate       1189 non-null   float64
 12  roas                  1192 non-null   float64
 13  ad_type               979 non-null    object
 14  audience_segment      908 non-null    object
 15  device_type           1008 non-null   object
 16  region                968 non-null    object
 17  bounce_rate           1195 non-null   float64
 18  avg_session_duration  561 non-null    object
 19  engagement_rate       1193 non-null   float64
 20  ad_position           734 non-null    object
dtypes: datetime64[ns](1), float64(11), int64(1), object(8)
memory usage: 197.0+ KB

In [43]:
q1=16173
q3=39147
iqr=q3-q1
lf=(q1)-1.5*(iqr)
lf

-18288.0

In [44]:
hf=q3+1.5*(iqr)
print(hf)

73608.0

In [45]:
df.loc[df['impressions'] >= 73608.0]

Empty DataFrame
Columns: [campaign_id, campaign_name, platform, date, impressions, clicks, cost, conversions, revenue, ctr, cpc, conversion_rate, roas, ad_type, audience_segment, device_type, region, bounce_rate, avg_session_duration, engagement_rate, ad_position]
Index: []

[0 rows x 21 columns]

In [46]:
df.describe()

,campaign_id,date,impressions,clicks,cost,conversions,revenue,ctr,cpc,conversion_rate,roas,bounce_rate,engagement_rate
count,1200.000000,1200,1195.000000,1189.000000,1192.000000,1193.000000,1194.000000,1189.000000,1189.000000,1189.000000,1192.000000,1195.000000,1193.000000
mean,1502.479167,2024-02-23 12:30:00,27658.066946,2565.777965,265.122659,249.744342,2778.121039,12.971985,0.228545,20.339403,15.044908,34.321339,44.696563
min,1001.000000,2024-01-01 00:00:00,5054.000000,100.000000,50.200000,10.000000,508.070000,0.250000,0.010000,0.210000,1.040000,20.000000,30.000000
25%,1250.750000,2024-02-15 00:00:00,16173.500000,1331.000000,140.575000,131.000000,1648.747500,4.960000,0.060000,5.010000,6.627500,27.000000,37.000000
50%,1505.000000,2024-03-10 00:00:00,27782.000000,2531.000000,255.875000,241.000000,2738.860000,9.380000,0.100000,9.820000,10.315000,34.000000,45.000000
75%,1749.250000,2024-03-10 00:00:00,39147.500000,3871.000000,378.585000,375.000000,3914.715000,16.410000,0.210000,18.930000,18.610000,42.000000,52.000000
max,2000.000000,2024-04-05 00:00:00,49865.000000,4997.000000,499.900000,499.000000,4997.340000,97.460000,4.570000,333.000000,88.030000,49.000000,59.000000
std,287.972886,NaN,13083.905300,1448.510447,131.358002,141.854375,1301.767604,12.724070,0.430080,35.806968,13.792969,8.727717,8.498725

In [47]:
# using count we can find null values. apan tharvu shakato konta column thevayacha konta nahi
# Mean आपल्याला सांगतो की कॉलममधला data सर्वसाधारणपणे कुठे केंद्रित आहे. जर mean आणि median मध्ये मोठा फरक असेल, तर डेटा skewed आहे (एकाच बाजूला झुकलेला).
# जर mean खूपच जास्त किंवा कमी वाटत असेल, तर कदाचित काही outlier values आहेत.
# Standard Deviation (std) म्हणजे डेटामधील विस्कळीतपणा (spread) किंवा values किती प्रमाणात mean पासून दूर आहेत ते मोजण्याचं एक मापदंड आहे.
# जर std कमी असेल तर सगळ्या values जवळपास आहेत.जर std जास्त असेल, तर काही values खूप जास्त किंवा कमी आहेत.
# std समजून घेतल्याशिवाय normalization किंवा standardization योग्य प्रकारे करता येत नाही.
# दोन कॉलममध्ये mean सारखा असला तरी ज्याचा std कमी आहे तो जास्त stable आणि विश्वासार्ह आहे.
# min आपल्याला सांगतो की त्या column मध्ये सर्वात कमी किंवा किमान कोणती value आहे.
# min- Outliers ओळखण्यासाठी (Too Low Values) कधी कधी एखादी value फारच कमी असते — आणि ती realistic वाटत नाही.
# उदा: Age कॉलमचा min = -5 असेल ⇒ चुकीचा डेटा आहे.
# min->Negative values जिथे नसाव्यात. Zero values जिथे अपेक्षित नाही. Extremely small numbers. Business Logic Validate करण्यासाठी
# 25% म्हणजे 1st Quartile (Q1) — हा डेटा मधील असा point आहे की 25% डेटा ह्याच्यापेक्षा कमी आहे आणि 75% डेटा ह्याच्यापेक्षा जास्त आहे.
# min, Q1, median, Q3, max हे एकत्र बघितल्यास डेटा कसा पसरलेला आहे ते समजतं.
# Outliers शोधण्यासाठी Q1 चा उपयोग फार महत्त्वाचा आहे.
# जर median (50%) आणि Q1 मध्ये मोठा फरक असेल, तर data skewed असू शकतो.
# 50% म्हणजे Median (मध्यमान) – हा डेटा मधला value आहे.म्हणजेच, डेटा ascending order मध्ये लावल्यावर, नक्की मधोमध येणारी value म्हणजे Median.
# 50%-Central Tendency समजण्यासाठी,Skewness (data झुकलेला आहे का?) समजण्यासाठी Median वर outliers चा प्रभाव कमी असतो.
# त्यामुळे जेव्हा dataset मध्ये outliers असतील तेव्हा median वापरणं योग्य असतं.
# 75% म्हणजे 3rd Quartile (Q3) – dataset मधील अशी value जिच्यापेक्षा 75% डेटा कमी आहे आणि 25% डेटा जास्त आहे.
# 75%->High Performers किंवा High Values segment शोधण्यासाठी

## 1.2 Column Name Standardization
Rename inconsistent, messy, or duplicate column names.

In [48]:
#df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

## 1.3 Handling Missing Values (Nulls)


Drop rows:
if condider over all dataset- जेव्हा missing rows फारच कमी असतात (जसं < 5%), तेव्हा drop करणं योग्य.

Drop specific columns
Too many nulls (> 50%)

Fill with Mean / Median / Mode
1) For Numerical Columns-use mean and median(if outliers exist)
2) For Categorical Columns- use mode

Forward Fill / Backward Fill-Time-series किंवा ordered data साठी वापरतात.

Custom Values Fill-Business knowledge वापरून specific values टाकणे.
ex- df['Age'].fillna(0, inplace=True)  # Age जर 0 असेल तर "Unknown"

Predictive Imputation (Advanced)- Missing values predict करणं using ML (Linear Regression, KNN)

In [49]:
# df.dropna(inplace=True)  # सगळ्या rows जिथे missing आहे ते काढून टाक

## 1.4 Handling Duplicate

## 1.5 Handling Incorrect Data Types

## 1.6 Outlier Detection & Treatment

## 1.7 data formating

## 1.8 Handling Invalid or Impossible Values
Logical validation: Negative age? Spend more than revenue?
Apply business rules.

## 1.9 Text Cleaning
Remove special characters, numbers, stopwords

Lowercase, lemmatize

## 1.10 correct spelling, replace, mapping

## 1.11 data normalization,scalling

## 1.12 data transformation-log, power

## 1.13 feature engineering-date feature,word count,

In [50]:
dataset_name.corr(method='pearsons').head(10)

NameError: name 'dataset_name' is not defined

In [ ]:
plt.scatterplot(x=dataset[c1],y=dataset[c2])

## 1.14 Encoding

## 1.15 data binning

## 1.16 data sampling

## 1.17 handling imbalanced data